### ISSUE TITLE
[SPEL] Unknown Function found in 005C6BE9

### ISSUE THREAD

**Issue by 003401E8** [eckserah/TES5Edit#10]
![image](https://user-images.githubusercontent.com/71900912/94330149-3ef2f880-ff87-11ea-819f-4c29b75b34d9.png)

SPEL\Effects\Effect\Conditions\Condition\CTDA - CTDA\Function has a Function with value <Unknown: 6000>

**Comment by eckserah** [comment]
I seem to have missed this one when doing the other ones. I'm looking for it now.

**Comment by eckserah** [comment]
fixed in f96c267
