### ISSUE TITLE
[FURN] CNAM & LNAM - Unknown 

### ISSUE THREAD

**Issue by 003401E8** [eckserah/TES5Edit#15]
There's not a lot to go on here, but the following FURN records are the only ones with CNAM & LNAM values set (which are unknown).

0038A8E2
CNAM - 4E 61 BC 00
LNAM - 08

0034E7D4
CNAM - 4E 61 BC 00
LNAM - 08

003A560C
CNAM - 4E 61 BC 00
LNAM - 08

0045107F
CNAM - 28 06 68 00
LNAM - 07

00368F86
CNAM - 50 54 00 00
LNAM - 06

002F78C4
CNAM - 3A B3 01 00
LNAM - 06

0047F99A
CNAM - B2 D0 0E 00
LNAM - 06

003CFB48
CNAM - 28 06 68 00
LNAM - 07

0052684C
CNAM - 78 90 00 00
LNAM - 05

**Comment by eckserah** [comment]
As you stated in the discord. These are default keypad code and default keypad code length. Fixed in 3396414
