### ISSUE TITLE
[SMQN] UNAM - Unknown

### ISSUE THREAD

**Issue by 003401E8** [eckserah/TES5Edit#16]
The following SMQN records are the only one to have a UNAM value - which is unknown.

00002838 - GQ_SceneKMK07Node
UNAM - 63 00 00 00

00077D86 - GQ_SceneKMK02Node
UNAM - 63 00 00 00

0033C645 - QP_TDM_Child_Branch 
UNAM - 02 00 00 00

0039FC6D - QP_TDM_OneLife_Child_Branch
UNAM - 02 00 00 00

**Comment by 003401E8** [comment]
![image](https://user-images.githubusercontent.com/71900912/94982346-6144c300-04ff-11eb-8b87-33ffd9197f32.png)

It looks like there were record changes made to all four listed, as they, and others, appear to have a more structured record defining UNAM. This is a change in FO76Edit 4.1.5z5.7

**Comment by eckserah** [comment]
That's because I fixed it :P
