### ISSUE TITLE
(FO76Edit64 v4.1.3.1; FO76 PTS v0.1.543.1) [COBJ:005DC0DE] <Unknown: 255> value found in Condition

### ISSUE THREAD

**Issue by 003401E8** [eckserah/TES5Edit#19]
![image](https://user-images.githubusercontent.com/71900912/94938166-16db2c00-0496-11eb-9757-cf116581e94a.png)

Credit to gilpo for the find.

**Comment by 003401E8** [comment]
Adding on, the Unknown of EB 79 5B 00 in little endian is [QUST:005B79EB], and in looking at others with different hex values in the condition, it looks like little endian value that points to a requirement of some sort. See picture for example.

![image](https://user-images.githubusercontent.com/71900912/94939181-5e15ec80-0497-11eb-8c98-39009ac6f245.png)

**Comment by eckserah** [comment]
Fixed
